services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway" # optional, kalau mau akses host db

networks:
  laravel:
    driver: bridge