services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsimpleapp
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge