services:
  wsimpleapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsimpleapp
    volumes:
      - ~/docker/volumes/wsimpleapp/storage:/var/www/storage
    restart: unless-stopped
    ports:
      - "9000"
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge